{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "telegraf.fullname" . }}
  labels:
    {{- include "telegraf.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
  {{- end }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.prometheus_client.listen }}
    targetPort: {{ .Values.prometheus_client.listen }}
    name: http
  selector:
    {{- include "telegraf.selectorLabels" . | nindent 4 }}
{{- end -}}
